[project]
name = "market-surveillance"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.8",
    "pandas>=3.0.0",
    "prettytable>=3.10.0",
    "scipy>=1.17.0",
]
